defaults:
  - default

optflow_pairs: 2490               # ≈ one pass over the train slice per epoch
data_subsample_ratio: 1

train_dataset_str: "
  + ${dataset.quantity_options.train.optflow_pairs} @ ${dataset.optflow_isaac.train.dataset_str}[:2490][::${dataset.quantity_options.train.data_subsample_ratio}]"
